# Generated by Django 5.2.1 on 2025-05-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
