# Generated by Django 5.2.1 on 2025-05-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_recurringtransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurringTransaction',
        ),
    ]
