# Generated by Django 5.2.1 on 2025-06-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
